name: Compile & Upload
on:
  push:
    branches: master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        SM_VERSION: ["1.10", "1.11"]
        
    steps:
      - uses: actions/checkout@v2
      
      - name: Set environment variables
        run: |
          git fetch --unshallow
          VERSION=$(git rev-list --count HEAD)
          SHORT=$(git describe --always --long --dirty)
          SOURCEMOD_PATH=$GITHUB_WORKSPACE/addons/sourcemod
          echo "PLUGIN_VERSION=${{ matrix.SM_VERSION }}.$VERSION.$SHORT" >> $GITHUB_ENV
          echo "SOURCEMOD_PATH=$SOURCEMOD_PATH" >> $GITHUB_ENV
          echo "SCRIPTS_PATH=$SOURCEMOD_PATH/scripting" >> $GITHUB_ENV
          echo "PLUGINS_PATH=$SOURCEMOD_PATH/plugins" >> $GITHUB_ENV
          
      - name: Setup SourcePawn Compiler ${{ matrix.SM_VERSION }}
        uses: rumblefrog/setup-sp@master
        with:
          version: ${{ matrix.SM_VERSION }}
          
      - name: Set GFLBans version
        run: |
          sed -i "s/<VERSION>/$PLUGIN_VERSION/g" $SCRIPTS_PATH/gflbans-core/variables.sp
          
      - name: Get Rest in Pawn inc files
        run: |
          git clone https://github.com/ErikMinekus/sm-ripext.git rip
          cp -r ./rip/pawn/scripting/include $SCRIPTS_PATH
          
      - name: Remove Rest in Pawn files
        run: |
          rm -rf rip
          
      - name: Compile GFLBans
        run: |
          spcomp -w234 -O2 -v2 -i $SCRIPTS_PATH/include $SCRIPTS_PATH/gflbans-core.sp
        working-directory: ${{ env.SCRIPTS_PATH }}
        
      - name: Move Compiled Plugins
        run: |
          rm -rf $PLUGINS_PATH
          mkdir -p $PLUGINS_PATH/
          rsync -av --include="*/" --include="*.smx" --exclude="*" --prune-empty-dirs --remove-source-files $SCRIPTS_PATH/ $PLUGINS_PATH/
          
      - name: Move addons folder to build
        run: |
          mkdir build
          mv ./addons build/
          
      - name: Remove unnessary files and folders from build
        run: |
          rm -rf addons/sourcemod/extensions
          rm -rf addons/sourcemod/configs/ripext
        working-directory: ./build
          
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: GFLBans.${{ env.PLUGIN_VERSION }}
          path: ./build
